trunk/Drocuments/Models/DTOs/Doctors.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Drocuments.Models.DTOs
{
    public class Doctorsmodel
    {
        public int id { set; get; }
        public string name { set; get; }
        public int specialization_id { set; get; }
        public string clinic_name { set; get; }
        public string address { set; get; }
        public string qualification { set; get; }
        public int rating { set; get; }
    }
}

trunk/Drocuments/Models/Doctors.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Drocuments.Models
{
    public class Doctors
    {
      
    }

}

trunk/Drocuments/Controllers/DoctorsController.cs
using Amazon;
using Drocuments.Models.DTOs;
using Repository;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebMatrix.WebData;


namespace Drocuments.Controllers
{
    public class DoctorsController : Controller
    {
        //
        // GET: /Doctors/
        DrocumentsEntities dc = new DrocumentsEntities();

        public ActionResult Index()
        {
            if (TempData["Message"] != null)
            {
                ViewBag.Message = TempData["Message"].ToString();
            }
            int id = WebSecurity.CurrentUserId;
            // dc.Configuration.ProxyCreationEnabled = false;

            List<doctor> data = dc.doctors.Where(p => p.id == id).ToList();
            return View(data);
          
        }
        public ActionResult Add()
        {
            Doctorsmodel model = new Doctorsmodel();
            int id = WebSecurity.CurrentUserId;
            model.id = id;
            return View(model);

        }
        [HttpPost ]
        public ActionResult Add(Doctorsmodel objdoc)
        {
            doctor doc = new doctor
            {
                id = objdoc.id,
                name = objdoc.name,
                specialization_id = objdoc.specialization_id,
                clinic_name = objdoc.clinic_name,
                address = objdoc.address,
                qualification = objdoc.qualification,
                rating = objdoc.rating
            };
            dc.doctors.Add(doc);
            dc.SaveChanges();
            Doctorsmodel model = new Doctorsmodel();


            return View(model);

        }

     
    }
}

trunk/Drocuments/Views/Doctors/Add.cshtml
@model   Drocuments.Models.DTOs.Doctorsmodel

@{
    ViewBag.Title = "Add";
 //Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("Add", "Doctors", FormMethod.Post, new { EncType = "multipart/form-data", id = "regForm" }))
{ 

@*@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)*@

    
    <div class="container">
            <div class="row">
                <div class="col-md-4">
                    <h1 class="signup-header"> Add Doctor </h1>
                </div>
                <div class="col-md-6">
                    @if (ViewBag.Message != null)
                    {
                        @ViewBag.Message
                    }
                </div>
                <div class="col-md-2">
                    <div class="row signup-form">
                        <div class="col-md-6">
                            <input type="reset" class="btn btn-default" value="Cancel" />
                        </div>
                        <div class="col-md-6">
                            <input type="submit" id="savefamily" class="btn btn-primary" value="Save" />
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <hr />
                </div>
            </div>
            <div>     
                            <div class="row">
                                <div class="col-md-9">
                                    <div class="row">
                                        <div class="col-md-4">
                                            @*<div class="form-group">
                                                    <span>UserId</span>
                                                    <div>
                                                        @Html.TextBox("UserId", null, new { @class = "form-control" })
                                                    </div>
                                                </div>*@
                                            @*<div class="form-group">*@
                                                                                               <div>
                                                    @Html.Hidden(Model.id.ToString())
                                              @*@Html.TextBox("id", null, new { @class = "form-control" })*@


                                                </div>
                                            @*</div>*@
                                            <div class="form-group">
                                                <span>Name</span>
                                                <div>
                                                    @Html.TextBox("name", null, new { @class = "form-control" })
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <span>Specialization_id</span>
                                                <div>
                                                    @Html.TextBox("specialization_id", null, new { @class = "form-control" })
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-md-4">
                                            <div class="form-group">

                                                <span>Clinic Name</span>
                                                <div>
                                                    @Html.TextBox("clinic_name", null, new { @class = "form-control" })
                                                </div>
                                            </div>
                                           
                                            <div class="form-group">

                                                <span>Address</span>
                                                <div>

                                                    @Html.TextBox("address", null, new { @class = "form-control" })
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-md-4">
                                            <div class="form-group">

                                                <span>qualification</span>
                                                <div>
                                                    @Html.TextBox("qualification", null, new { @class = "form-control" })
                                                </div>
                                            </div>
                                            <div class="form-group">

                                                <span>Rating</span>
                                                <div>
                                                    @Html.TextBox("reating", null, new { @class = "form-control" })
                                                </div>
                                            </div>
                                         
                                        
                                        
                            </div></div></div></div></div></div>

              } 
@*<div>
    @Html.ActionLink("Back to List", "Index")
</div>*@

@*@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}*@

trunk/Drocuments/Views/Doctors/Index.cshtml
@model  List<Repository.doctor>

@{
    ViewBag.Title = "Index";
   Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <div class="row signup-form">
        <div class="col-md-12" align="center">

            <div class="col-md-6">
                <table class="table">
                    <thead>
                        <tr>
                            <td>
                               Id
                            </td>
                            <td>
                               Name
                            </td>
                            <td>
                                Qualification
                            </td>
                            <td>
                              Clinic Name
                            </td>
                            <td>
                                Address
                            </td>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @item.id
                                </td>
                                <td>
                                    @item.name
                                </td>
                                <td>
                                    @item.qualification
                                </td>
                                <td>
                                    @item.clinic_name
                                </td>
                                <td>
                                    @item.address
                                </td>
                                <td>
                                    <a>Edit</a>
                                    <a>Delete</a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>

            </div>
            <div class="col-md-6">
                <img src="~/Images/family_icon.png" class="img img-circle img-responsive img-thumbnail" width="200" />
                <h1 class="text-center signup-header">
                    Welcome
                </h1>
                <span>You can add  doctors  by clicking below</span>
                <form class="signup-form">
                    <div class="form-group">
                        @Html.ActionLink("Add Doctors", "Add", "Doctors", null, new { @class = "btn btn-drocument" })
                    </div>
                </form>
            </div>




        </div>
    </div>
</div>

@*<div>
    @Html.ActionLink("Back to List", "Index")
</div>*@

@*@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}*@