trunk/Drocuments/Models/DTOs/FamilyMembers.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Drocuments.Models.DTOs
{
    public class FamilyMembers
    {
        public int Id { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> FamilyMemberId { get; set; }
        public string FamilyMemberEmail { get; set; }
        public Nullable<int> RelationID { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<bool> Status { get; set; }

    }
     public class relations
     {
         public int RelationId { get; set; }
         public string RelationName { get; set; }
         public bool StatusId { get; set; }
         public System.DateTime CreatedDate { get; set; }
         public System.DateTime UpdatedDate { get; set; }
     }
}


  

trunk/Drocuments/Controllers/FamilyMembersController.cs
using Drocuments.Models.DTOs;
using Repository;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebMatrix.WebData;

using System.Data.SqlClient;
using System.Data;
namespace Drocuments.Controllers
{

    public class FamilyMembersController : Controller
    {
        //
        // GET: /FamilyMembers/
        DrocumentsEntities dc = new DrocumentsEntities();

        public ActionResult Index()
        {
            if (TempData["Message"] != null)
            {
                ViewBag.Message = TempData["Message"].ToString();
            }
            int id = WebSecurity.CurrentUserId;
            // dc.Configuration.ProxyCreationEnabled = false;
            var data = dc.tbl_Family_Member.Where(p => p.UserID == id ).ToList();
            return View(data);
        }
        public ActionResult Add()
        {

            FamilyMembers model = new FamilyMembers();
            int id = WebSecurity.CurrentUserId;
            model.UserID = id;
            return View(model);
           
            
        }
        [HttpPost]
        public ActionResult Add(FamilyMembers objaddfamilymembers)
        {
            //int id = WebSecurity.CurrentUserId;
            tbl_Family_Member family = new tbl_Family_Member
            {
                UserID = objaddfamilymembers.UserID,
                UpdatedBy = objaddfamilymembers.UserID,
                CreatedOn = objaddfamilymembers.CreatedOn,
                IsActive = true,
                UpdatedOn = DateTime.Now,
                FamilyMemberEmail = objaddfamilymembers.FamilyMemberEmail,
                CreatedBy = objaddfamilymembers.UserID,
                Status = objaddfamilymembers.Status
            };
            dc.tbl_Family_Member.Add(family);
            dc.SaveChanges();
            return View(objaddfamilymembers);

            
                   }
        
  
//            @Html.DayPilotScheduler("dps", new DayPilotSchedulerConfig
//{
//    BackendUrl = Url.Content("~/Scheduler/Backend"),
//    CssOnly = true,
//    CssClassPrefix = "scheduler_white"
//})
        }

    }

trunk/Drocuments/Views/FamilyMembers/Index.cshtml
@model  List<Repository.tbl_Family_Member>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script src="@Url.Content("~/Scripts/DayPilot/daypilot-all.min.js")" type="text/javascript"></script>
<link href="@Url.Content("~/Themes/scheduler_white.css")" rel="stylesheet" type="text/css" />
<div class="container">
    <div class="row signup-form">
        <div class="col-md-12" align="center">

            <div class="col-md-6">
                <table class="table">
                    <thead>
                        <tr>
                            <td>
                                Member Id
                            </td>
                            <td>
                                FamilyMember EmailId
                            </td>
                            <td>
                                Relation
                            </td>
                            <td>
                                Action
                            </td>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @item.Id
                                </td>
                                <td>
                                    @item.FamilyMemberEmail
                                </td>
                                <td>
                                    @item.RelationID
                                </td>
                                <td>
                                    <a>Edit</a>
                                    <a>Delete</a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>

            </div>
            <div class="col-md-6">
                <img src="~/Images/family_icon.png" class="img img-circle img-responsive img-thumbnail" width="200" />
                <h1 class="text-center signup-header">
                    Welcome
                </h1>
                <span>You can add  your FamilyMembers  by clicking below</span>
                <form class="signup-form">
                    <div class="form-group">
                        @Html.ActionLink("Add Family Memebers", "Add", "FamilyMembers", null, new { @class = "btn btn-drocument" })
                    </div>
                </form>
            </div>



         
        </div>
    </div>
</div>

trunk/Drocuments/Views/FamilyMembers/Relations.cshtml
@model Drocuments.Models.DTOs.FamilyMembers

@{
    ViewBag.Title = "Relations";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Relations</h2>